Repository Programmers-HandsUp/BE-handsup, pull requests merged in 2024-03, with the labels that each got.

#50 [feat] : 경매 추천 API
  api/src/main/java/dev/handsup/auction/controller/AuctionApiController.java
  api/src/test/java/dev/handsup/auction/controller/AuctionApiControllerTest.java
  api/src/test/java/dev/handsup/search/controller/SearchApiControllerTest.java
  core/src/main/generated/dev/handsup/auction/domain/QAuction.java
  core/src/main/java/dev/handsup/auction/domain/Auction.java
  core/src/main/java/dev/handsup/auction/dto/mapper/AuctionMapper.java
  core/src/main/java/dev/handsup/auction/dto/response/AuctionDetailResponse.java
  core/src/main/java/dev/handsup/auction/dto/response/AuctionSimpleResponse.java
  core/src/main/java/dev/handsup/auction/dto/response/RecommendAuctionResponse.java
  core/src/main/java/dev/handsup/auction/exception/AuctionErrorCode.java
  core/src/main/java/dev/handsup/auction/repository/auction/AuctionQueryRepository.java
  core/src/main/java/dev/handsup/auction/repository/auction/AuctionQueryRepositoryImpl.java
  core/src/main/java/dev/handsup/auction/service/AuctionService.java
  core/src/main/java/dev/handsup/bidding/dto/request/RegisterBiddingRequest.java
  core/src/main/java/dev/handsup/bidding/service/BiddingService.java
  core/src/test/java/dev/handsup/auction/repository/auction/AuctionQueryRepositoryImplTest.java
  core/src/test/java/dev/handsup/auction/service/AuctionServiceTest.java
  core/src/test/java/dev/handsup/search/service/SearchServiceTest.java
  core/src/testFixtures/java/dev/handsup/fixture/AuctionFixture.java
Labels: feat, 빠른 리뷰가 필요해요!

#52 [feat] : 경매 상태 변경 스케줄러 구현
  api/src/main/java/dev/handsup/common/config/CorsConfig.java
  core/src/main/java/dev/handsup/auction/domain/Auction.java
  core/src/main/java/dev/handsup/auction/domain/auction_field/AuctionStatus.java
  core/src/main/java/dev/handsup/auction/repository/auction/AuctionQueryRepositoryImpl.java
  core/src/main/java/dev/handsup/auction/repository/auction/AuctionRepository.java
  core/src/main/java/dev/handsup/auction/scheduler/AuctionScheduler.java
  core/src/main/java/dev/handsup/common/config/SchedulerConfig.java
  core/src/test/java/dev/handsup/auction/repository/auction/AuctionRepositoryTest.java
  core/src/testFixtures/java/dev/handsup/fixture/AuctionFixture.java
Labels: feat, refactor, 빠른 리뷰가 필요해요!

#48 [feat] : 리뷰 등록API / 경매 리뷰 조회 API / 리뷰 라벨 설계
  api/src/main/java/dev/handsup/auth/jwt/JwtInterceptor.java
  api/src/main/java/dev/handsup/common/config/WebConfig.java
  api/src/main/java/dev/handsup/review/controller/ReviewApiController.java
  api/src/main/java/dev/handsup/user/dto/JoinUserApiRequest.java
  api/src/test/java/dev/handsup/auth/JwtAuthorizationArgumentResolverTest.java
  api/src/test/java/dev/handsup/auth/JwtInterceptorTest.java
  api/src/test/java/dev/handsup/auth/controller/AuthApiControllerTest.java
  api/src/test/java/dev/handsup/bidding/controller/BiddingApiControllerTest.java
  api/src/test/java/dev/handsup/bookmark/controller/BookmarkApiControllerTest.java
  api/src/test/java/dev/handsup/common/support/ApiTestSupport.java
  api/src/test/java/dev/handsup/review/controller/ReviewApiControllerTest.java
  api/src/test/java/dev/handsup/user/controller/UserApiControllerTest.java
  core/src/main/generated/dev/handsup/comment/domain/QComment.java
  core/src/main/generated/dev/handsup/review/domain/QReview.java
  core/src/main/generated/dev/handsup/review/domain/QReviewLabel.java
  core/src/main/java/dev/handsup/auction/domain/product/Product.java
  core/src/main/java/dev/handsup/auction/dto/mapper/AuctionMapper.java
  core/src/main/java/dev/handsup/auction/dto/request/RegisterAuctionRequest.java
  core/src/main/java/dev/handsup/auction/service/AuctionService.java
  core/src/main/java/dev/handsup/auth/dto/AuthMapper.java
  core/src/main/java/dev/handsup/auth/dto/request/LoginRequest.java
  core/src/main/java/dev/handsup/bidding/dto/BiddingMapper.java
  core/src/main/java/dev/handsup/bidding/service/BiddingService.java
  core/src/main/java/dev/handsup/bookmark/dto/BookmarkMapper.java
  core/src/main/java/dev/handsup/bookmark/service/BookmarkService.java
  core/src/main/java/dev/handsup/comment/domain/Comment.java
  core/src/main/java/dev/handsup/common/dto/CommonMapper.java
  core/src/main/java/dev/handsup/common/exception/CommonErrorCode.java
  core/src/main/java/dev/handsup/common/exception/CommonValidationError.java
  core/src/main/java/dev/handsup/common/service/EntityManagementService.java
  core/src/main/java/dev/handsup/image/exception/ImageErrorCode.java
  core/src/main/java/dev/handsup/review/domain/Review.java
  core/src/main/java/dev/handsup/review/domain/ReviewInterReviewLabel.java
  core/src/main/java/dev/handsup/review/domain/ReviewLabel.java
  core/src/main/java/dev/handsup/review/domain/ReviewLabelValue.java
  core/src/main/java/dev/handsup/review/domain/UserReviewLabel.java
  core/src/main/java/dev/handsup/review/dto/ReviewMapper.java
  core/src/main/java/dev/handsup/review/dto/request/RegisterReviewRequest.java
  core/src/main/java/dev/handsup/review/dto/response/ReviewResponse.java
  core/src/main/java/dev/handsup/review/exception/ReviewErrorCode.java
  core/src/main/java/dev/handsup/review/repository/ReviewInterReviewLabelRepository.java
  core/src/main/java/dev/handsup/review/repository/ReviewLabelRepository.java
  core/src/main/java/dev/handsup/review/repository/ReviewRepository.java
  core/src/main/java/dev/handsup/review/service/ReviewService.java
  core/src/main/java/dev/handsup/search/service/SearchService.java
  core/src/main/java/dev/handsup/user/domain/User.java
  core/src/main/java/dev/handsup/user/exception/UserErrorCode.java
  core/src/main/java/dev/handsup/user/repository/UserReviewLabelRepository.java
  core/src/main/java/dev/handsup/user/service/UserService.java
  core/src/test/java/dev/handsup/auction/repository/auction/AuctionRepositoryTest.java
  core/src/test/java/dev/handsup/bidding/repository/BiddingRepositoryTest.java
  core/src/test/java/dev/handsup/bookmark/service/BookmarkServiceTest.java
  core/src/test/java/dev/handsup/review/service/ReviewServiceTest.java
  core/src/test/java/dev/handsup/support/DataJpaTestSupport.java
  core/src/test/java/dev/handsup/user/repository/UserReviewLabelRepositoryTest.java
  core/src/testFixtures/java/dev/handsup/fixture/ReviewFixture.java
  core/src/testFixtures/java/dev/handsup/fixture/ReviewLabelFixture.java
  core/src/testFixtures/java/dev/handsup/fixture/UserReviewLabelFixture.java
Labels: feat, refactor

#56 [feat] : 회원가입 이메일 중복 체크 API
  api/src/main/java/dev/handsup/user/controller/UserApiController.java
  api/src/test/java/dev/handsup/user/controller/UserApiControllerTest.java
  core/src/main/java/dev/handsup/user/dto/request/EmailAvailibilityRequest.java
  core/src/main/java/dev/handsup/user/dto/response/EmailAvailabilityResponse.java
  core/src/main/java/dev/handsup/user/service/UserService.java
Labels: feat

#59 [feat] : Bidding 응답값 추가
  api/src/test/java/dev/handsup/bidding/controller/BiddingApiControllerTest.java
  core/src/main/java/dev/handsup/bidding/dto/BiddingMapper.java
  core/src/main/java/dev/handsup/bidding/dto/response/BiddingResponse.java
  core/src/test/java/dev/handsup/bidding/service/BiddingServiceTest.java
Labels: feat

#60 [feat] : 회원 가입 API 개선
  .gitignore
  api/src/main/java/dev/handsup/user/controller/UserApiController.java
  api/src/main/java/dev/handsup/user/dto/UserApiMapper.java
  api/src/test/java/dev/handsup/auction/controller/AuctionApiControllerTest.java
  api/src/test/java/dev/handsup/common/support/ApiTestSupport.java
  api/src/test/java/dev/handsup/user/controller/UserApiControllerTest.java
  core/src/main/generated/dev/handsup/auction/domain/QAuction.java
  core/src/main/generated/dev/handsup/auction/domain/auction_field/QTradingLocation.java
  core/src/main/generated/dev/handsup/auction/domain/product/QProduct.java
  core/src/main/generated/dev/handsup/auction/domain/product/QProductImage.java
  core/src/main/generated/dev/handsup/auction/domain/product/product_category/QProductCategory.java
  core/src/main/generated/dev/handsup/auction/domain/product/product_category/QProductCategoryLike.java
  core/src/main/generated/dev/handsup/auth/domain/QAuth.java
  core/src/main/generated/dev/handsup/auth/domain/QBlacklistToken.java
  core/src/main/generated/dev/handsup/bidding/domain/QBidding.java
  core/src/main/generated/dev/handsup/bookmark/domain/QBookmark.java
  core/src/main/generated/dev/handsup/chat/domain/QChatMessage.java
  core/src/main/generated/dev/handsup/chat/domain/QChatRoom.java
  core/src/main/generated/dev/handsup/comment/domain/QComment.java
  core/src/main/generated/dev/handsup/common/entity/QTimeBaseEntity.java
  core/src/main/generated/dev/handsup/notification/domain/QNotification.java
  core/src/main/generated/dev/handsup/review/domain/QReview.java
  core/src/main/generated/dev/handsup/review/domain/QReviewInterReviewLabel.java
  core/src/main/generated/dev/handsup/review/domain/QReviewLabel.java
  core/src/main/generated/dev/handsup/review/domain/QUserReviewLabel.java
  core/src/main/generated/dev/handsup/user/domain/QAddress.java
  core/src/main/generated/dev/handsup/user/domain/QUser.java
  core/src/main/java/dev/handsup/auction/domain/product/product_category/PreferredProductCategory.java
  core/src/main/java/dev/handsup/auction/domain/product/product_category/ProductCategory.java
  core/src/main/java/dev/handsup/auction/domain/product/product_category/ProductCategoryValue.java
  core/src/main/java/dev/handsup/auction/dto/mapper/AuctionMapper.java
  core/src/main/java/dev/handsup/auction/repository/auction/AuctionQueryRepositoryImpl.java
  core/src/main/java/dev/handsup/auction/repository/product/PreferredProductCategoryRepository.java
  core/src/main/java/dev/handsup/auction/repository/product/ProductCategoryRepository.java
  core/src/main/java/dev/handsup/auction/service/AuctionService.java
  core/src/main/java/dev/handsup/user/dto/request/JoinUserRequest.java
  core/src/main/java/dev/handsup/user/service/UserService.java
  core/src/test/java/dev/handsup/auction/repository/auction/AuctionQueryRepositoryImplTest.java
  core/src/test/java/dev/handsup/auction/service/AuctionServiceTest.java
  core/src/test/java/dev/handsup/user/service/UserServiceTest.java
Labels: feat, refactor, 빠른 리뷰가 필요해요!

#61 [refactor] : 리뷰서비스 registerReview() 개선
  api/src/test/java/dev/handsup/review/controller/ReviewApiControllerTest.java
  core/src/main/java/dev/handsup/auction/domain/product/ProductStatus.java
  core/src/main/java/dev/handsup/review/domain/UserReviewLabel.java
  core/src/main/java/dev/handsup/review/service/ReviewService.java
  core/src/test/java/dev/handsup/user/repository/UserReviewLabelRepositoryTest.java
Labels: refactor

#65 [feat] : 채팅방 생성 API, 유저 채팅방 조회 API 구현
  .gitignore
  api/src/main/java/dev/handsup/controller/ChatRoomApiController.java
  api/src/test/java/dev/handsup/auth/JwtInterceptorTest.java
  api/src/test/java/dev/handsup/chat/service/ChatRoomServiceTest.java
  api/src/test/java/dev/handsup/common/support/ApiTestSupport.java
  api/src/test/java/dev/handsup/controller/ChatRoomApiControllerTest.java
  api/src/test/java/dev/handsup/review/controller/ReviewApiControllerTest.java
  api/src/test/java/dev/handsup/user/controller/UserApiControllerTest.java
  core/src/main/java/dev/handsup/auction/repository/auction/AuctionRepository.java
  core/src/main/java/dev/handsup/auction/service/AuctionService.java
  core/src/main/java/dev/handsup/bidding/service/BiddingService.java
  core/src/main/java/dev/handsup/bookmark/service/BookmarkService.java
  core/src/main/java/dev/handsup/chat/domain/ChatMessage.java
  core/src/main/java/dev/handsup/chat/domain/ChatRoom.java
  core/src/main/java/dev/handsup/chat/dto/ChatMapper.java
  core/src/main/java/dev/handsup/chat/dto/response/ChatRoomSimpleResponse.java
  core/src/main/java/dev/handsup/chat/dto/response/RegisterChatRoomResponse.java
  core/src/main/java/dev/handsup/chat/exception/ChatErrorCode.java
  core/src/main/java/dev/handsup/chat/repository/ChatRoomRepository.java
  core/src/main/java/dev/handsup/chat/service/ChatRoomService.java
  core/src/main/java/dev/handsup/comment/domain/Comment.java
  core/src/main/java/dev/handsup/common/exception/CommonErrorCode.java
  core/src/main/java/dev/handsup/common/service/EntityManagementService.java
  core/src/main/java/dev/handsup/review/domain/Review.java
  core/src/main/java/dev/handsup/review/domain/ReviewLabel.java
  core/src/main/java/dev/handsup/review/domain/UserReviewLabel.java
  core/src/main/java/dev/handsup/review/dto/request/RegisterReviewRequest.java
  core/src/main/java/dev/handsup/review/exception/ReviewErrorCode.java
  core/src/main/java/dev/handsup/review/service/ReviewService.java
  core/src/main/java/dev/handsup/user/domain/User.java
  core/src/main/java/dev/handsup/user/exception/UserErrorCode.java
  core/src/main/java/dev/handsup/user/service/UserService.java
  core/src/test/java/dev/handsup/auction/service/AuctionServiceTest.java
  core/src/test/java/dev/handsup/bidding/repository/BiddingRepositoryTest.java
  core/src/test/java/dev/handsup/bidding/service/BiddingServiceTest.java
  core/src/test/java/dev/handsup/chat/repository/ChatRoomRepositoryTest.java
  core/src/test/java/dev/handsup/review/service/ReviewServiceTest.java
  core/src/test/java/dev/handsup/user/repository/UserReviewLabelRepositoryTest.java
  core/src/test/java/dev/handsup/user/service/UserServiceTest.java
  core/src/testFixtures/java/dev/handsup/fixture/ChatRoomFixture.java
  core/src/testFixtures/java/dev/handsup/fixture/UserFixture.java
Labels: feat, refactor

#63 [feat] : 사용자 리뷰라벨 조회 API
  api/src/main/java/dev/handsup/user/controller/UserApiController.java
  api/src/test/java/dev/handsup/user/controller/UserApiControllerTest.java
  core/src/main/java/dev/handsup/review/domain/UserReviewLabel.java
  core/src/main/java/dev/handsup/user/domain/Address.java
  core/src/main/java/dev/handsup/user/dto/UserMapper.java
  core/src/main/java/dev/handsup/user/dto/response/UserReviewLabelResponse.java
  core/src/main/java/dev/handsup/user/repository/UserReviewLabelRepository.java
  core/src/main/java/dev/handsup/user/service/UserService.java
  core/src/testFixtures/java/dev/handsup/fixture/UserFixture.java
Labels: feat

#73 [feat] : 사용자 리뷰 조회 API
  api/src/main/java/dev/handsup/user/controller/UserApiController.java
  api/src/test/java/dev/handsup/user/controller/UserApiControllerTest.java
  core/src/main/java/dev/handsup/review/exception/ReviewErrorCode.java
  core/src/main/java/dev/handsup/review/repository/ReviewRepository.java
  core/src/main/java/dev/handsup/user/dto/UserMapper.java
  core/src/main/java/dev/handsup/user/dto/response/UserReviewResponse.java
  core/src/main/java/dev/handsup/user/service/UserService.java
  core/src/testFixtures/java/dev/handsup/fixture/AuctionFixture.java
  core/src/testFixtures/java/dev/handsup/fixture/ReviewFixture.java
Labels: feat

#75 [feat] : websocket + stomp로 채팅 메시지 구현
  api/build.gradle
  api/src/main/java/dev/handsup/chat/controller/ChatMessageApiController.java
  api/src/main/java/dev/handsup/common/config/WebSocketConfig.java
  api/src/main/java/dev/handsup/image/controller/ImageApiController.java
  api/src/test/java/dev/handsup/auction/controller/AuctionApiControllerTest.java
  api/src/test/java/dev/handsup/chat/controller/ChatRoomApiControllerTest.java
  api/src/test/java/dev/handsup/chat/controller/WebSocketTest.java
  core/src/main/java/dev/handsup/bidding/service/BiddingService.java
  core/src/main/java/dev/handsup/chat/domain/ChatMessage.java
  core/src/main/java/dev/handsup/chat/dto/ChatMapper.java
  core/src/main/java/dev/handsup/chat/dto/ChatMessageMapper.java
  core/src/main/java/dev/handsup/chat/dto/request/ChatMessageRequest.java
  core/src/main/java/dev/handsup/chat/dto/response/ChatMessageResponse.java
  core/src/main/java/dev/handsup/chat/exception/ChatErrorCode.java
  core/src/main/java/dev/handsup/chat/exception/ChatRoomErrorCode.java
  core/src/main/java/dev/handsup/chat/repository/ChatMessageRepository.java
  core/src/main/java/dev/handsup/chat/service/ChatMessageService.java
  core/src/main/java/dev/handsup/chat/service/ChatRoomService.java
  core/src/testFixtures/java/dev/handsup/fixture/ChatMessageFixture.java
Labels: feat

#78 [feat] : FCM 메시지 전송
  api/build.gradle
  api/src/main/java/dev/handsup/auth/controller/AuthApiController.java
  api/src/main/java/dev/handsup/user/dto/JoinUserApiRequest.java
  api/src/test/java/dev/handsup/auth/controller/AuthApiControllerTest.java
  api/src/test/java/dev/handsup/common/support/ApiTestSupport.java
  api/src/test/java/dev/handsup/user/controller/UserApiControllerTest.java
  api/src/test/resources/application.yml
  api/src/test/resources/firebase/firebase_service_account.json
  core/build.gradle
  core/src/main/java/dev/handsup/auth/dto/request/LoginRequest.java
  core/src/main/java/dev/handsup/bookmark/service/BookmarkService.java
  core/src/main/java/dev/handsup/common/config/FCMConfig.java
  core/src/main/java/dev/handsup/notification/domain/NotificationType.java
  core/src/main/java/dev/handsup/notification/domain/exception/NotificationErrorCode.java
  core/src/main/java/dev/handsup/notification/domain/exception/NotificationException.java
  core/src/main/java/dev/handsup/notification/domain/repository/FCMTokenRepository.java
  core/src/main/java/dev/handsup/notification/domain/service/FCMService.java
  core/src/main/java/dev/handsup/notification/domain/service/NotificationService.java
  core/src/main/resources/firebase/firebase_service_account.json
  core/src/test/java/dev/handsup/auction/repository/auction/AuctionQueryRepositoryImplTest.java
  core/src/test/java/dev/handsup/auction/repository/auction/AuctionRepositoryTest.java
  core/src/test/java/dev/handsup/auth/service/AuthServiceTest.java
  core/src/test/java/dev/handsup/bidding/repository/BiddingRepositoryTest.java
  core/src/test/java/dev/handsup/bookmark/service/BookmarkServiceTest.java
  core/src/test/java/dev/handsup/chat/repository/ChatRoomRepositoryTest.java
  core/src/test/java/dev/handsup/common/support/DataJpaTestSupport.java
  core/src/test/java/dev/handsup/notification/domain/service/FCMServiceTest.java
  core/src/test/java/dev/handsup/user/repository/UserReviewLabelRepositoryTest.java
  core/src/test/resources/application.yml
  core/src/test/resources/firebase/firebase_service_account.json
Labels: feat

#77 [feat] : 거래 완료 및 거래 취소 API 구현
  api/src/main/java/dev/handsup/bidding/controller/BiddingApiController.java
  api/src/main/java/dev/handsup/chat/controller/ChatRoomApiController.java
  api/src/test/java/dev/handsup/auction/controller/AuctionApiControllerTest.java
  api/src/test/java/dev/handsup/bidding/controller/BiddingApiControllerTest.java
  api/src/test/java/dev/handsup/chat/controller/ChatRoomApiControllerTest.java
  api/src/test/java/dev/handsup/chat/controller/WebSocketTest.java
  api/src/test/java/dev/handsup/controller/ChatRoomApiControllerTest.java
  core/src/main/java/dev/handsup/auction/domain/Auction.java
  core/src/main/java/dev/handsup/auction/domain/auction_field/TradingLocation.java
  core/src/main/java/dev/handsup/auction/dto/mapper/AuctionMapper.java
  core/src/main/java/dev/handsup/auction/dto/response/AuctionDetailResponse.java
  core/src/main/java/dev/handsup/auction/dto/response/UserInfo.java
  core/src/main/java/dev/handsup/bidding/domain/Bidding.java
  core/src/main/java/dev/handsup/bidding/domain/TradingStatus.java
  core/src/main/java/dev/handsup/bidding/dto/BiddingMapper.java
  core/src/main/java/dev/handsup/bidding/dto/response/BiddingResponse.java
  core/src/main/java/dev/handsup/bidding/exception/BiddingErrorCode.java
  core/src/main/java/dev/handsup/bidding/repository/BiddingRepository.java
  core/src/main/java/dev/handsup/bidding/service/BiddingService.java
  core/src/main/java/dev/handsup/chat/domain/ChatRoom.java
  core/src/main/java/dev/handsup/chat/dto/ChatRoomMapper.java
  core/src/main/java/dev/handsup/chat/dto/response/ChatRoomDetailResponse.java
  core/src/main/java/dev/handsup/chat/repository/ChatRoomRepository.java
  core/src/main/java/dev/handsup/chat/service/ChatRoomService.java
  core/src/main/java/dev/handsup/user/domain/Address.java
  core/src/test/java/dev/handsup/bidding/service/BiddingServiceTest.java
  core/src/test/java/dev/handsup/chat/repository/ChatRoomRepositoryTest.java
  core/src/test/java/dev/handsup/chat/service/ChatRoomServiceTest.java
  core/src/testFixtures/java/dev/handsup/fixture/BiddingFixture.java
  core/src/testFixtures/java/dev/handsup/fixture/ChatRoomFixture.java
Labels: feat

#82 [feat] : 유저 맞춤 경매 추천 API
  api/src/main/java/dev/handsup/auction/controller/AuctionApiController.java
  api/src/test/java/dev/handsup/auction/controller/AuctionApiControllerTest.java
  core/src/main/java/dev/handsup/auction/dto/mapper/AuctionMapper.java
  core/src/main/java/dev/handsup/auction/repository/auction/AuctionQueryRepository.java
  core/src/main/java/dev/handsup/auction/repository/auction/AuctionQueryRepositoryImpl.java
  core/src/main/java/dev/handsup/auction/repository/product/PreferredProductCategoryRepository.java
  core/src/main/java/dev/handsup/auction/service/AuctionService.java
  core/src/main/java/dev/handsup/bidding/domain/Bidding.java
  core/src/main/java/dev/handsup/bidding/exception/BiddingErrorCode.java
  core/src/main/java/dev/handsup/chat/dto/ChatRoomMapper.java
  core/src/main/java/dev/handsup/chat/dto/response/ChatRoomDetailResponse.java
  core/src/main/java/dev/handsup/chat/service/ChatRoomService.java
  core/src/main/java/dev/handsup/user/domain/Address.java
  core/src/test/java/dev/handsup/auction/repository/auction/AuctionQueryRepositoryImplTest.java
  core/src/test/java/dev/handsup/auction/service/AuctionServiceTest.java
Labels: feat

#84 [fix] : TradingLocation 엔티티 name 속성 원상복구
  core/src/main/java/dev/handsup/auction/domain/auction_field/TradingLocation.java
  core/src/main/java/dev/handsup/auction/dto/mapper/AuctionMapper.java
Labels: fix

#86 [refactor] : 경매 검색 필터 수정
  core/src/main/java/dev/handsup/auction/repository/auction/AuctionQueryRepositoryImpl.java
  core/src/test/java/dev/handsup/auction/repository/auction/AuctionQueryRepositoryImplTest.java
Labels: refactor

#88 [feat] : 알림 구현
  api/src/main/java/dev/handsup/auth/controller/AuthApiController.java
  api/src/main/java/dev/handsup/notification/controller/NotificationApiController.java
  api/src/main/java/dev/handsup/user/controller/UserApiController.java
  api/src/test/java/dev/handsup/auth/controller/AuthApiControllerTest.java
  api/src/test/java/dev/handsup/bookmark/controller/BookmarkApiControllerTest.java
  api/src/test/java/dev/handsup/common/support/ApiTestSupport.java
  api/src/test/java/dev/handsup/notification/controller/NotificationApiControllerTest.java
  core/src/main/java/dev/handsup/auth/dto/request/LoginRequest.java
  core/src/main/java/dev/handsup/bidding/dto/request/RegisterBiddingRequest.java
  core/src/main/java/dev/handsup/bidding/service/BiddingService.java
  core/src/main/java/dev/handsup/bookmark/exception/BookmarkErrorCode.java
  core/src/main/java/dev/handsup/bookmark/exception/BookmarkException.java
  core/src/main/java/dev/handsup/bookmark/service/BookmarkService.java
  core/src/main/java/dev/handsup/common/config/FCMConfig.java
  core/src/main/java/dev/handsup/notification/domain/Notification.java
  core/src/main/java/dev/handsup/notification/domain/service/FCMService.java
  core/src/main/java/dev/handsup/notification/domain/service/NotificationService.java
  core/src/main/java/dev/handsup/notification/dto/NotificationMapper.java
  core/src/main/java/dev/handsup/notification/dto/request/SaveFCMTokenRequest.java
  core/src/main/java/dev/handsup/notification/dto/response/CountUserNotificationsResponse.java
  core/src/main/java/dev/handsup/notification/dto/response/NotificationResponse.java
  core/src/main/java/dev/handsup/notification/exception/NotificationErrorCode.java
  core/src/main/java/dev/handsup/notification/exception/NotificationException.java
  core/src/main/java/dev/handsup/notification/repository/FCMTokenRepository.java
  core/src/main/java/dev/handsup/notification/repository/NotificationRepository.java
  core/src/main/java/dev/handsup/notification/service/FCMService.java
  core/src/main/java/dev/handsup/notification/service/NotificationCleanupService.java
  core/src/main/java/dev/handsup/notification/service/NotificationService.java
  core/src/main/java/dev/handsup/user/domain/User.java
  core/src/main/java/dev/handsup/user/dto/request/JoinUserRequest.java
  core/src/main/resources/firebase/firebase_service_account.json
  core/src/test/java/dev/handsup/auth/service/AuthServiceTest.java
  core/src/test/java/dev/handsup/bookmark/service/BookmarkServiceTest.java
  core/src/test/java/dev/handsup/notification/domain/service/FCMServiceTest.java
  core/src/testFixtures/java/dev/handsup/fixture/AuctionFixture.java
Labels: feat

#90 [fix] : sql syntax 에러 해결
  api/src/test/java/dev/handsup/bidding/controller/BiddingApiControllerTest.java
  core/src/main/java/dev/handsup/bidding/dto/BiddingMapper.java
  core/src/main/java/dev/handsup/bookmark/domain/Bookmark.java
Labels: fix

#97 [feat] : 인메모리 브로커 Redis pub/sub으로 변경
  api/src/main/java/dev/handsup/chat/MessagePublisher.java
  api/src/main/java/dev/handsup/chat/MessageSubscriber.java
  api/src/main/java/dev/handsup/chat/controller/ChatMessageApiController.java
  api/src/main/java/dev/handsup/common/config/RedisConfig.java
  api/src/main/java/dev/handsup/common/config/WebSocketConfig.java
  api/src/test/java/dev/handsup/chat/controller/WebSocketTest.java
  core/src/main/java/dev/handsup/common/config/RedisConfig.java
Labels: feat

#100 [feat] : webSocketConfig, CorsConfig에서 CORS 설정 수정
  api/src/main/java/dev/handsup/chat/controller/ChatMessageApiController.java
  api/src/main/java/dev/handsup/common/config/CorsConfig.java
  api/src/main/java/dev/handsup/common/config/WebConfig.java
  api/src/main/java/dev/handsup/common/config/WebSocketConfig.java
  api/src/test/java/dev/handsup/chat/controller/WebSocketTest.java
  core/src/main/java/dev/handsup/chat/dto/ChatRoomMapper.java
  core/src/main/java/dev/handsup/chat/dto/response/ChatRoomDetailResponse.java
Labels: feat, refactor, 빠른 리뷰가 필요해요!

#94 [feat] : 마이페이지 프로필 조회
  api/src/main/java/dev/handsup/user/controller/UserApiController.java
  api/src/test/java/dev/handsup/auction/controller/AuctionApiControllerTest.java
  api/src/test/java/dev/handsup/common/support/ApiTestSupport.java
  api/src/test/java/dev/handsup/review/controller/ReviewApiControllerTest.java
  api/src/test/java/dev/handsup/user/controller/UserApiControllerTest.java
  core/src/main/java/dev/handsup/auction/domain/product/product_category/ProductCategory.java
  core/src/main/java/dev/handsup/auction/service/AuctionService.java
  core/src/main/java/dev/handsup/common/config/FCMConfig.java
  core/src/main/java/dev/handsup/review/service/ReviewService.java
  core/src/main/java/dev/handsup/user/domain/User.java
  core/src/main/java/dev/handsup/user/dto/response/UserProfileResponse.java
  core/src/main/java/dev/handsup/user/service/UserService.java
  core/src/test/java/dev/handsup/auction/repository/auction/AuctionQueryRepositoryImplTest.java
  core/src/test/java/dev/handsup/user/service/UserServiceTest.java
  core/src/testFixtures/java/dev/handsup/fixture/AuctionFixture.java
  core/src/testFixtures/java/dev/handsup/fixture/ProductFixture.java
Labels: feat

#105 [feat] : 입찰 등록 API 개선
  api/src/test/java/dev/handsup/auth/JwtAuthorizationArgumentResolverTest.java
  api/src/test/java/dev/handsup/bidding/controller/BiddingApiControllerTest.java
  api/src/test/java/dev/handsup/bookmark/controller/BookmarkApiControllerTest.java
  api/src/test/java/dev/handsup/chat/controller/ChatRoomApiControllerTest.java
  api/src/test/java/dev/handsup/chat/controller/WebSocketTest.java
  api/src/test/java/dev/handsup/common/support/ApiTestSupport.java
  api/src/test/java/dev/handsup/notification/controller/NotificationApiControllerTest.java
  api/src/test/java/dev/handsup/user/controller/UserApiControllerTest.java
  core/src/main/java/dev/handsup/auction/domain/Auction.java
  core/src/main/java/dev/handsup/bidding/exception/BiddingErrorCode.java
  core/src/main/java/dev/handsup/bidding/service/BiddingService.java
  core/src/test/java/dev/handsup/auction/repository/auction/AuctionRepositoryTest.java
  core/src/test/java/dev/handsup/auction/service/AuctionServiceTest.java
  core/src/test/java/dev/handsup/auth/service/AuthServiceTest.java
  core/src/test/java/dev/handsup/bidding/repository/BiddingRepositoryTest.java
  core/src/test/java/dev/handsup/bidding/service/BiddingServiceTest.java
  core/src/test/java/dev/handsup/bookmark/service/BookmarkServiceTest.java
  core/src/test/java/dev/handsup/chat/repository/ChatRoomRepositoryTest.java
  core/src/test/java/dev/handsup/chat/service/ChatRoomServiceTest.java
  core/src/test/java/dev/handsup/notification/domain/service/FCMServiceTest.java
  core/src/test/java/dev/handsup/review/service/ReviewServiceTest.java
  core/src/test/java/dev/handsup/user/repository/UserReviewLabelRepositoryTest.java
  core/src/test/java/dev/handsup/user/service/UserServiceTest.java
  core/src/testFixtures/java/dev/handsup/fixture/AuctionFixture.java
  core/src/testFixtures/java/dev/handsup/fixture/ReviewFixture.java
  core/src/testFixtures/java/dev/handsup/fixture/UserFixture.java
  core/src/testFixtures/java/dev/handsup/fixture/UserReviewLabelFixture.java
Labels: feat

#107 [feat] : 경매 입찰 종료 시 스케줄러로 경매, 입찰 상태 변경
  api/src/test/java/dev/handsup/bidding/controller/BiddingApiControllerTest.java
  core/src/main/java/dev/handsup/auction/domain/Auction.java
  core/src/main/java/dev/handsup/auction/exception/AuctionErrorCode.java
  core/src/main/java/dev/handsup/auction/repository/auction/AuctionQueryRepository.java
  core/src/main/java/dev/handsup/auction/repository/auction/AuctionQueryRepositoryImpl.java
  core/src/main/java/dev/handsup/auction/repository/auction/AuctionRepository.java
  core/src/main/java/dev/handsup/auction/scheduler/AuctionScheduler.java
  core/src/main/java/dev/handsup/bidding/repository/BiddingQueryRepository.java
  core/src/main/java/dev/handsup/bidding/repository/BiddingQueryRepositoryImpl.java
  core/src/main/java/dev/handsup/bidding/repository/BiddingRepository.java
  core/src/main/java/dev/handsup/bidding/scheduler/BiddingScheduler.java
  core/src/main/java/dev/handsup/bidding/service/BiddingService.java
  core/src/test/java/dev/handsup/auction/repository/auction/AuctionQueryRepositoryImplTest.java
  core/src/test/java/dev/handsup/auction/repository/auction/AuctionRepositoryTest.java
  core/src/test/java/dev/handsup/bidding/repository/BiddingQueryRepositoryTest.java
  core/src/test/java/dev/handsup/bidding/service/BiddingServiceTest.java
  core/src/test/java/dev/handsup/config/TestAuditingConfig.java
  core/src/testFixtures/java/dev/handsup/fixture/BiddingFixture.java
Labels: feat, 빠른 리뷰가 필요해요!

#109 [fix] : Swagger CORS 오류 수정
  api/src/main/java/dev/handsup/common/config/CorsConfig.java
  api/src/main/java/dev/handsup/common/config/SwaggerConfig.java
Labels: fix

#104 [feat] : 리뷰 등록 API 개선
  api/src/main/java/dev/handsup/review/controller/ReviewApiController.java
  api/src/test/java/dev/handsup/review/controller/ReviewApiControllerTest.java
  core/src/main/java/dev/handsup/auction/domain/auction_field/TradingLocation.java
  core/src/main/java/dev/handsup/bidding/domain/Bidding.java
  core/src/main/java/dev/handsup/bidding/dto/BiddingMapper.java
  core/src/main/java/dev/handsup/bidding/dto/response/BiddingResponse.java
  core/src/main/java/dev/handsup/bidding/exception/BiddingErrorCode.java
  core/src/main/java/dev/handsup/bidding/repository/BiddingRepository.java
  core/src/main/java/dev/handsup/bidding/service/BiddingService.java
  core/src/main/java/dev/handsup/notification/domain/NotificationType.java
  core/src/main/java/dev/handsup/notification/service/FCMService.java
  core/src/main/java/dev/handsup/review/dto/ReviewMapper.java
  core/src/main/java/dev/handsup/review/dto/response/ReviewDetailResponse.java
  core/src/main/java/dev/handsup/review/dto/response/ReviewSimpleResponse.java
  core/src/main/java/dev/handsup/review/service/ReviewService.java
  core/src/test/java/dev/handsup/review/service/ReviewServiceTest.java
  core/src/testFixtures/java/dev/handsup/fixture/BiddingFixture.java
  core/src/testFixtures/java/dev/handsup/fixture/ReviewFixture.java
Labels: feat

#114 [feat] : 로그인 된 사용자 정보 조회 API 추가, 이메일 중복 체크 에러 해결
  api/src/main/java/dev/handsup/user/controller/UserApiController.java
  api/src/test/java/dev/handsup/user/controller/UserApiControllerTest.java
  core/src/main/java/dev/handsup/user/dto/request/EmailAvailabilityRequest.java
  core/src/main/java/dev/handsup/user/dto/response/UserDetailResponse.java
  core/src/main/java/dev/handsup/user/service/UserService.java
Labels: feat

#112 [feat] : 알림 전송 5가지 유형 추가
  api/src/main/java/dev/handsup/common/config/SwaggerConfig.java
  api/src/main/java/dev/handsup/review/controller/ReviewApiController.java
  api/src/test/java/dev/handsup/auth/JwtInterceptorTest.java
  api/src/test/java/dev/handsup/bidding/controller/BiddingApiControllerTest.java
  api/src/test/java/dev/handsup/bookmark/controller/BookmarkApiControllerTest.java
  api/src/test/java/dev/handsup/review/controller/ReviewApiControllerTest.java
  api/src/test/java/dev/handsup/user/controller/UserApiControllerTest.java
  api/src/test/resources/application.yml
  core/src/main/java/dev/handsup/auction/service/AuctionService.java
  core/src/main/java/dev/handsup/auth/exception/AuthException.java
  core/src/main/java/dev/handsup/auth/service/AuthService.java
  core/src/main/java/dev/handsup/auth/service/JwtProvider.java
  core/src/main/java/dev/handsup/bidding/exception/BiddingErrorCode.java
  core/src/main/java/dev/handsup/bidding/service/BiddingService.java
  core/src/main/java/dev/handsup/bookmark/exception/BookmarkException.java
  core/src/main/java/dev/handsup/bookmark/service/BookmarkService.java
  core/src/main/java/dev/handsup/chat/service/ChatMessageService.java
  core/src/main/java/dev/handsup/chat/service/ChatRoomService.java
  core/src/main/java/dev/handsup/common/exception/ValidationException.java
  core/src/main/java/dev/handsup/notification/exception/NotificationException.java
  core/src/main/java/dev/handsup/notification/service/FCMService.java
  core/src/main/java/dev/handsup/review/domain/ReviewLabelValue.java
  core/src/test/java/dev/handsup/auth/service/JwtProviderTest.java
  core/src/test/java/dev/handsup/bidding/service/BiddingServiceTest.java
  core/src/test/java/dev/handsup/notification/domain/service/FCMServiceTest.java
  core/src/test/java/dev/handsup/review/service/ReviewServiceTest.java
  core/src/test/resources/application.yml
  core/src/testFixtures/java/dev/handsup/fixture/ReviewLabelFixture.java
Labels: feat

#111 [ feat] : 채팅방 메시지 조회 API 개선 및 응답값 추가
  api/src/test/java/dev/handsup/chat/controller/ChatRoomApiControllerTest.java
  core/src/main/java/dev/handsup/auction/domain/Auction.java
  core/src/main/java/dev/handsup/bidding/repository/BiddingRepository.java
  core/src/main/java/dev/handsup/bidding/service/BiddingService.java
  core/src/main/java/dev/handsup/chat/dto/ChatRoomMapper.java
  core/src/main/java/dev/handsup/chat/dto/response/ChatRoomDetailResponse.java
  core/src/main/java/dev/handsup/chat/service/ChatMessageService.java
  core/src/main/java/dev/handsup/chat/service/ChatRoomService.java
  core/src/test/java/dev/handsup/auction/repository/auction/AuctionQueryRepositoryImplTest.java
  core/src/test/java/dev/handsup/chat/service/ChatRoomServiceTest.java
Labels: feat, refactor

#119 [feat] : 채팅 메시지 최신순으로 정렬
  api/src/test/java/dev/handsup/chat/controller/ChatRoomApiControllerTest.java
  api/src/test/java/dev/handsup/user/controller/UserApiControllerTest.java
  core/src/main/java/dev/handsup/bidding/domain/Bidding.java
  core/src/main/java/dev/handsup/bidding/exception/BiddingErrorCode.java
  core/src/main/java/dev/handsup/chat/repository/ChatMessageRepository.java
  core/src/main/java/dev/handsup/chat/service/ChatRoomService.java
  core/src/test/java/dev/handsup/chat/service/ChatRoomServiceTest.java
Labels: feat

#123 [feat] : 댓글 생성 및 조회
  api/src/main/java/dev/handsup/comment/controller/CommentApiController.java
  api/src/test/java/dev/handsup/comment/controller/CommentApiControllerTest.java
  core/src/main/java/dev/handsup/auction/domain/Auction.java
  core/src/main/java/dev/handsup/bidding/repository/BiddingRepository.java
  core/src/main/java/dev/handsup/chat/repository/ChatRoomRepository.java
  core/src/main/java/dev/handsup/comment/dto/request/RegisterCommentRequest.java
  core/src/main/java/dev/handsup/comment/dto/response/CommentResponse.java
  core/src/main/java/dev/handsup/comment/exception/CommentErrorCode.java
  core/src/main/java/dev/handsup/comment/mapper/CommentMapper.java
  core/src/main/java/dev/handsup/comment/repository/CommentRepository.java
  core/src/main/java/dev/handsup/comment/service/CommentService.java
  core/src/test/java/dev/handsup/comment/service/CommentServiceTest.java
  core/src/testFixtures/java/dev/handsup/fixture/CommentFixture.java
Labels: feat

#121 [feat] : 마이페이지 구매내역, 판매내역 API
  api/src/main/java/dev/handsup/auth/controller/AuthApiController.java
  api/src/main/java/dev/handsup/image/controller/ImageApiController.java
  api/src/main/java/dev/handsup/user/controller/UserApiController.java
  api/src/test/java/dev/handsup/user/controller/UserApiControllerTest.java
  core/src/main/java/dev/handsup/auction/domain/auction_field/AuctionStatus.java
  core/src/main/java/dev/handsup/auction/dto/response/AuctionSimpleResponse.java
  core/src/main/java/dev/handsup/auth/dto/AuthMapper.java
  core/src/main/java/dev/handsup/bidding/repository/BiddingRepository.java
  core/src/main/java/dev/handsup/notification/dto/NotificationMapper.java
  core/src/main/java/dev/handsup/notification/dto/response/NotificationResponse.java
  core/src/main/java/dev/handsup/notification/service/FCMService.java
  core/src/main/java/dev/handsup/notification/service/NotificationService.java
  core/src/main/java/dev/handsup/user/service/UserService.java
  core/src/test/java/dev/handsup/bidding/repository/BiddingQueryRepositoryTest.java
  core/src/testFixtures/java/dev/handsup/fixture/AuctionFixture.java
  core/src/testFixtures/java/dev/handsup/fixture/BiddingFixture.java
Labels: feat

#126 [fix] : 리뷰 등록 API 통합 테스트 에러 해결
  api/src/test/java/dev/handsup/review/controller/ReviewApiControllerTest.java
Labels: fix

#137 [feat] : 구매내역, 판매내역, 사용자 리뷰라벨 조회 API 응답 값 추가 및 수정
  api/src/main/java/dev/handsup/user/controller/UserApiController.java
  core/src/main/java/dev/handsup/auction/domain/Auction.java
  core/src/main/java/dev/handsup/bidding/service/BiddingService.java
  core/src/main/java/dev/handsup/notification/service/NotificationService.java
  core/src/main/java/dev/handsup/user/domain/User.java
  core/src/main/java/dev/handsup/user/dto/UserMapper.java
  core/src/main/java/dev/handsup/user/dto/response/UserBuyHistoryResponse.java
  core/src/main/java/dev/handsup/user/dto/response/UserSaleHistoryResponse.java
  core/src/main/java/dev/handsup/user/service/UserService.java
Labels: feat

#138 [fix] : 유저의 읽은 알림 수를 데이터베이스에 반영
  core/src/main/java/dev/handsup/auction/domain/Auction.java
  core/src/main/java/dev/handsup/notification/service/NotificationService.java
  core/src/main/java/dev/handsup/user/dto/response/UserBuyHistoryResponse.java
  core/src/main/java/dev/handsup/user/dto/response/UserSaleHistoryResponse.java
Labels: fix

#143 [feat] : 쿠키 세팅, 댓글 알림 추가, 판매내역 오류 수정
  api/src/test/java/dev/handsup/comment/controller/CommentApiControllerTest.java
  api/src/test/java/dev/handsup/review/controller/ReviewApiControllerTest.java
  api/src/test/java/dev/handsup/user/controller/UserApiControllerTest.java
  core/src/main/java/dev/handsup/auction/repository/auction/AuctionRepository.java
  core/src/main/java/dev/handsup/auth/dto/AuthMapper.java
  core/src/main/java/dev/handsup/bidding/repository/BiddingRepository.java
  core/src/main/java/dev/handsup/comment/service/CommentService.java
  core/src/main/java/dev/handsup/review/domain/ReviewLabelValue.java
  core/src/main/java/dev/handsup/user/service/UserService.java
  core/src/test/java/dev/handsup/comment/service/CommentServiceTest.java
  core/src/test/java/dev/handsup/review/service/ReviewServiceTest.java
  core/src/test/java/dev/handsup/user/repository/UserReviewLabelRepositoryTest.java
  core/src/testFixtures/java/dev/handsup/fixture/ReviewLabelFixture.java
Labels: fix, feat

#145 EC2 배포 시 서버 시간 UTC -> KST로 설정
  .github/workflows/ci.yml
  api/src/main/java/dev/handsup/HandsUpApplication.java
  core/src/main/java/dev/handsup/auction/dto/request/RegisterAuctionRequest.java
  core/src/main/java/dev/handsup/auction/repository/auction/AuctionRepository.java
Labels: feat

#152 [fix] : 수신자 bidder로 고정된 오류 해결
  api/src/test/java/dev/handsup/auction/controller/AuctionApiControllerTest.java
  core/src/main/java/dev/handsup/auction/dto/mapper/AuctionMapper.java
  core/src/main/java/dev/handsup/chat/domain/ChatRoom.java
  core/src/main/java/dev/handsup/chat/service/ChatRoomService.java
  core/src/test/java/dev/handsup/auction/service/AuctionServiceTest.java
Labels: fix, feat

#148 [feat] : 캐싱 도입, 알림 토큰 에러, 댓글 알림 타입 수정
  api/build.gradle
  api/src/main/java/dev/handsup/auction/controller/AuctionApiController.java
  api/src/main/java/dev/handsup/common/config/CacheConfig.java
  api/src/main/java/dev/handsup/common/domain/CacheType.java
  core/build.gradle
  core/src/main/java/dev/handsup/comment/service/CommentService.java
  core/src/main/java/dev/handsup/notification/service/FCMService.java
  core/src/test/java/dev/handsup/notification/domain/service/FCMServiceTest.java
  insert_auction_dummy_data.sql
  insert_product_dummy_data.sql
  insert_product_image_dummy_data.sql
Labels: fix, feat

#150 [feat] : 분산락 활용해 동시성 이슈 처리
  core/build.gradle
  core/src/main/java/dev/handsup/auction/domain/Auction.java
  core/src/main/java/dev/handsup/bidding/domain/Bidding.java
  core/src/main/java/dev/handsup/bidding/dto/BiddingMapper.java
  core/src/main/java/dev/handsup/bidding/repository/BiddingRepository.java
  core/src/main/java/dev/handsup/bidding/service/BiddingService.java
  core/src/main/java/dev/handsup/common/config/RedissonConfig.java
  core/src/main/java/dev/handsup/common/redisson/AopForTransaction.java
  core/src/main/java/dev/handsup/common/redisson/CustomSpringELParser.java
  core/src/main/java/dev/handsup/common/redisson/DistributeLock.java
  core/src/main/java/dev/handsup/common/redisson/DistributeLockAop.java
  core/src/main/java/dev/handsup/common/redisson/LockErrorCode.java
  core/src/test/java/dev/handsup/bidding/repository/BiddingConcurrencyTest.java
  core/src/test/java/dev/handsup/bidding/service/BiddingServiceTest.java
  core/src/testFixtures/java/dev/handsup/fixture/BiddingFixture.java
Labels: feat
