Repository Programmers-HandsUp/BE-handsup, pull requests merged in 2024-02, with the labels that each got.

#5 [feat] : 예외처리 템플릿 추가
  src/main/java/com/example/handsup/common/exception/CommonValidationError.java
  src/main/java/com/example/handsup/common/exception/ErrorCode.java
  src/main/java/com/example/handsup/common/exception/ErrorResponseTemplate.java
  src/main/java/com/example/handsup/common/exception/GlobalExceptionHandler.java
  src/main/java/com/example/handsup/common/exception/NotFoundException.java
  src/main/java/com/example/handsup/common/exception/ValidationException.java
Labels: feat, 빠른 리뷰가 필요해요!

#15 [feat] : 엔티티 세팅
  core/src/main/java/com/core/common/TimeBaseEntity.java
  core/src/main/java/com/core/domain/auction/Auction.java
  core/src/main/java/com/core/domain/auction/AuctionImage.java
  core/src/main/java/com/core/domain/auction/Bookmark.java
  core/src/main/java/com/core/domain/auction/Comment.java
  core/src/main/java/com/core/domain/auction/auction_category/ProductCategory.java
  core/src/main/java/com/core/domain/auction/auction_category/ProductCategoryLike.java
  core/src/main/java/com/core/domain/auction/auction_category/ProductCategoryValue.java
  core/src/main/java/com/core/domain/auction/auction_field/AuctionStatus.java
  core/src/main/java/com/core/domain/auction/auction_field/Coordinate.java
  core/src/main/java/com/core/domain/auction/auction_field/ProductStatus.java
  core/src/main/java/com/core/domain/auction/auction_field/PurchaseTime.java
  core/src/main/java/com/core/domain/auction/auction_field/TradeMethod.java
  core/src/main/java/com/core/domain/auction/history/BiddingHistory.java
  core/src/main/java/com/core/domain/auction/history/BuyingHistory.java
  core/src/main/java/com/core/domain/auction/history/SellingHistory.java
  core/src/main/java/com/core/domain/chat/ChatMessage.java
  core/src/main/java/com/core/domain/chat/ChatRoom.java
  core/src/main/java/com/core/domain/notification/Notification.java
  core/src/main/java/com/core/domain/notification/NotificationType.java
  core/src/main/java/com/core/domain/review/Review.java
  core/src/main/java/com/core/domain/review/ReviewLabel.java
  core/src/main/java/com/core/domain/review/ReviewLabelValue.java
  core/src/main/java/com/core/domain/review/UserReviewLabel.java
  core/src/main/java/com/core/domain/user/Address.java
  core/src/main/java/com/core/domain/user/User.java
Labels: feat, 빠른 리뷰가 필요해요!

#25 [feat] : 테스트 예외 케이스 추가
  META-INF/MANIFEST.MF
  api/src/main/java/dev/handsup/auction/controller/AuctionController.java
  api/src/test/java/dev/handsup/auction/controller/AuctionControllerTest.java
  api/src/test/java/dev/handsup/common/support/ApiTestSupport.java
  core/build.gradle
  core/src/main/java/dev/handsup/auction/domain/Auction.java
  core/src/main/java/dev/handsup/auction/domain/auction_field/PurchaseTime.java
  core/src/main/java/dev/handsup/auction/domain/auction_field/TradeMethod.java
  core/src/main/java/dev/handsup/auction/domain/product/Product.java
  core/src/main/java/dev/handsup/auction/domain/product/ProductStatus.java
  core/src/main/java/dev/handsup/auction/exception/AuctionErrorCode.java
  core/src/test/java/dev/handsup/auction/service/AuctionServiceTest.java
  core/src/testFixtures/java/dev/handsup/support/DatabaseCleaner.java
  core/src/testFixtures/java/dev/handsup/support/DatabaseCleanerExtension.java
Labels: feat

#26 [feat] : 유저 회원가입 API - 2
  api/src/main/java/dev/handsup/user/controller/UserApiController.java
  api/src/main/java/dev/handsup/user/dto/ApiUserMapper.java
  api/src/main/java/dev/handsup/user/dto/JoinUserApiRequest.java
  api/src/test/java/dev/handsup/user/controller/UserApiControllerTest.java
  core/src/main/java/dev/handsup/user/domain/User.java
  core/src/main/java/dev/handsup/user/dto/UserMapper.java
  core/src/main/java/dev/handsup/user/dto/request/JoinUserRequest.java
  core/src/main/java/dev/handsup/user/dto/request/UserJoinRequest.java
  core/src/main/java/dev/handsup/user/dto/response/JoinUserResponse.java
  core/src/main/java/dev/handsup/user/dto/response/UserJoinResponse.java
  core/src/main/java/dev/handsup/user/exception/UserErrorCode.java
  core/src/main/java/dev/handsup/user/service/UserService.java
  core/src/test/java/dev/handsup/user/service/UserServiceTest.java
  core/src/testFixtures/java/dev/handsup/fixture/UserFixture.java
Labels: feat, refactor

#29 [feat] : JWT 인증 인가 세팅
  api/src/main/java/dev/handsup/auction/controller/AuctionController.java
  api/src/main/java/dev/handsup/auth/annotation/NoAuth.java
  api/src/main/java/dev/handsup/auth/controller/AuthApiController.java
  api/src/main/java/dev/handsup/auth/dto/AuthApiMapper.java
  api/src/main/java/dev/handsup/auth/dto/AuthApiRequest.java
  api/src/main/java/dev/handsup/auth/dto/TokenReIssueApiRequest.java
  api/src/main/java/dev/handsup/auth/jwt/JwtAuthorization.java
  api/src/main/java/dev/handsup/auth/jwt/JwtAuthorizationArgumentResolver.java
  api/src/main/java/dev/handsup/auth/jwt/JwtInterceptor.java
  api/src/main/java/dev/handsup/common/config/WebConfig.java
  api/src/main/java/dev/handsup/user/controller/UserApiController.java
  api/src/main/java/dev/handsup/user/dto/UserApiMapper.java
  api/src/test/java/dev/handsup/auth/JwtAuthorizationArgumentResolverTest.java
  api/src/test/java/dev/handsup/auth/JwtInterceptorTest.java
  api/src/test/java/dev/handsup/auth/controller/AuthApiControllerTest.java
  api/src/test/resources/application.yml
  core/src/main/java/dev/handsup/auth/domain/Auth.java
  core/src/main/java/dev/handsup/auth/domain/BlacklistToken.java
  core/src/main/java/dev/handsup/auth/dto/request/AuthRequest.java
  core/src/main/java/dev/handsup/auth/dto/response/AuthResponse.java
  core/src/main/java/dev/handsup/auth/exception/AuthErrorCode.java
  core/src/main/java/dev/handsup/auth/exception/AuthException.java
  core/src/main/java/dev/handsup/auth/repository/AuthRepository.java
  core/src/main/java/dev/handsup/auth/repository/BlacklistTokenRepository.java
  core/src/main/java/dev/handsup/auth/service/AuthService.java
  core/src/main/java/dev/handsup/auth/service/JwtProvider.java
  core/src/main/java/dev/handsup/user/domain/User.java
  core/src/main/java/dev/handsup/user/dto/request/JoinUserRequest.java
  core/src/test/java/dev/handsup/auth/service/AuthServiceTest.java
  core/src/test/java/dev/handsup/auth/service/JwtProviderTest.java
  core/src/test/java/dev/handsup/user/service/UserServiceTest.java
  core/src/test/resources/application.yml
  core/src/testFixtures/java/dev/handsup/fixture/UserFixture.java
Labels: feat, chore

#33 [feat] : 경매 검색 API
  .gitignore
  api/src/main/java/dev/handsup/auction/controller/AuctionApiController.java
  api/src/main/java/dev/handsup/auction/controller/AuctionController.java
  api/src/main/java/dev/handsup/auction/dto/ApiAuctionMapper.java
  api/src/main/java/dev/handsup/auth/dto/AuthApiRequest.java
  api/src/main/java/dev/handsup/auth/jwt/JwtAuthorization.java
  api/src/main/java/dev/handsup/user/controller/UserApiController.java
  api/src/test/java/dev/handsup/auction/controller/AuctionApiControllerTest.java
  api/src/test/java/dev/handsup/auction/controller/AuctionControllerTest.java
  api/src/test/java/dev/handsup/auth/JwtAuthorizationArgumentResolverTest.java
  api/src/test/java/dev/handsup/auth/JwtInterceptorTest.java
  api/src/test/java/dev/handsup/auth/controller/AuthApiControllerTest.java
  core/build.gradle
  core/src/main/java/dev/handsup/auction/domain/Auction.java
  core/src/main/java/dev/handsup/auction/domain/auction_field/TradingLocation.java
  core/src/main/java/dev/handsup/auction/domain/product/Product.java
  core/src/main/java/dev/handsup/auction/domain/product/product_category/ProductCategory.java
  core/src/main/java/dev/handsup/auction/dto/AuctionResponse.java
  core/src/main/java/dev/handsup/auction/dto/mapper/AuctionMapper.java
  core/src/main/java/dev/handsup/auction/dto/request/AuctionSearchCondition.java
  core/src/main/java/dev/handsup/auction/dto/request/RegisterAuctionRequest.java
  core/src/main/java/dev/handsup/auction/dto/response/AuctionResponse.java
  core/src/main/java/dev/handsup/auction/repository/auction/AuctionQueryRepository.java
  core/src/main/java/dev/handsup/auction/repository/auction/AuctionQueryRepositoryImpl.java
  core/src/main/java/dev/handsup/auction/repository/auction/AuctionRepository.java
  core/src/main/java/dev/handsup/auction/repository/product/ProductCategoryRepository.java
  core/src/main/java/dev/handsup/auction/service/AuctionService.java
  core/src/main/java/dev/handsup/auth/dto/request/AuthRequest.java
  core/src/main/java/dev/handsup/auth/service/JwtProvider.java
  core/src/main/java/dev/handsup/common/config/QueryDslConfig.java
  core/src/main/java/dev/handsup/common/dto/PageResponse.java
  core/src/main/java/dev/handsup/user/domain/User.java
  core/src/main/java/dev/handsup/user/dto/request/JoinUserRequest.java
  core/src/test/java/dev/handsup/HandsUpApplicationTests.java
  core/src/test/java/dev/handsup/auction/repository/auction/AuctionQueryRepositoryImplTest.java
  core/src/test/java/dev/handsup/auction/service/AuctionServiceTest.java
  core/src/test/java/dev/handsup/auth/service/JwtProviderTest.java
  core/src/test/java/dev/handsup/support/DataJpaTestSupport.java
  core/src/testFixtures/java/dev/handsup/fixture/AuctionFixture.java
Labels: feat

#32 [feat] : 입찰 등록, 단건 조회, 3개 조회 API
  api/src/main/java/dev/handsup/bidding/controller/BiddingApiController.java
  api/src/main/java/dev/handsup/user/controller/UserApiController.java
  api/src/test/java/dev/handsup/auth/JwtAuthorizationArgumentResolverTest.java
  api/src/test/java/dev/handsup/auth/controller/AuthApiControllerTest.java
  api/src/test/java/dev/handsup/bidding/controller/BiddingApiControllerTest.java
  api/src/test/java/dev/handsup/common/support/ApiTestSupport.java
  api/src/test/java/dev/handsup/user/controller/UserApiControllerTest.java
  api/src/test/resources/application.yml
  core/src/main/java/dev/handsup/auction/domain/Auction.java
  core/src/main/java/dev/handsup/auction/exception/AuctionErrorCode.java
  core/src/main/java/dev/handsup/auction/service/AuctionService.java
  core/src/main/java/dev/handsup/bidding/domain/Bidding.java
  core/src/main/java/dev/handsup/bidding/dto/BiddingMapper.java
  core/src/main/java/dev/handsup/bidding/dto/request/RegisterBiddingRequest.java
  core/src/main/java/dev/handsup/bidding/dto/response/RegisterBiddingResponse.java
  core/src/main/java/dev/handsup/bidding/exception/BiddingErrorCode.java
  core/src/main/java/dev/handsup/bidding/repository/BiddingRepository.java
  core/src/main/java/dev/handsup/bidding/service/BiddingService.java
  core/src/test/java/dev/handsup/auction/repository/auction/AuctionQueryRepositoryImplTest.java
  core/src/test/java/dev/handsup/auction/service/AuctionServiceTest.java
  core/src/test/java/dev/handsup/auth/service/AuthServiceTest.java
  core/src/test/java/dev/handsup/bidding/repository/BiddingRepositoryTest.java
  core/src/test/java/dev/handsup/bidding/service/BiddingServiceTest.java
  core/src/test/java/dev/handsup/support/DataJpaTestSupport.java
  core/src/test/java/dev/handsup/user/service/UserServiceTest.java
  core/src/test/resources/application.yml
  core/src/testFixtures/java/dev/handsup/fixture/AuctionFixture.java
  core/src/testFixtures/java/dev/handsup/fixture/UserFixture.java
Labels: feat, refactor

#35 [feat] : 북마크 API 개발
  .gitignore
  api/src/main/java/dev/handsup/auction/controller/AuctionApiController.java
  api/src/main/java/dev/handsup/bookmark/controller/BookmarkApiController.java
  api/src/test/java/dev/handsup/auction/controller/AuctionApiControllerTest.java
  api/src/test/java/dev/handsup/bidding/controller/BiddingApiControllerTest.java
  api/src/test/java/dev/handsup/bookmark/controller/BookmarkApiControllerTest.java
  api/src/test/java/dev/handsup/common/support/ApiTestSupport.java
  core/src/main/generated/dev/handsup/auction/domain/QAuction.java
  core/src/main/generated/dev/handsup/auction/domain/QComment.java
  core/src/main/generated/dev/handsup/auction/domain/auction_field/QTradingLocation.java
  core/src/main/generated/dev/handsup/auction/domain/product/QProduct.java
  core/src/main/generated/dev/handsup/auction/domain/product/QProductImage.java
  core/src/main/generated/dev/handsup/auction/domain/product/product_category/QProductCategory.java
  core/src/main/generated/dev/handsup/auction/domain/product/product_category/QProductCategoryLike.java
  core/src/main/generated/dev/handsup/auth/domain/QAuth.java
  core/src/main/generated/dev/handsup/auth/domain/QBlacklistToken.java
  core/src/main/generated/dev/handsup/bidding/domain/QBidding.java
  core/src/main/generated/dev/handsup/bookmark/domain/QBookmark.java
  core/src/main/generated/dev/handsup/chat/domain/QChatMessage.java
  core/src/main/generated/dev/handsup/chat/domain/QChatRoom.java
  core/src/main/generated/dev/handsup/common/entity/QTimeBaseEntity.java
  core/src/main/generated/dev/handsup/notification/domain/QNotification.java
  core/src/main/generated/dev/handsup/review/domain/QReview.java
  core/src/main/generated/dev/handsup/review/domain/QReviewInterReviewLabel.java
  core/src/main/generated/dev/handsup/review/domain/QReviewLabel.java
  core/src/main/generated/dev/handsup/review/domain/QUserReviewLabel.java
  core/src/main/generated/dev/handsup/user/domain/QAddress.java
  core/src/main/generated/dev/handsup/user/domain/QUser.java
  core/src/main/java/dev/handsup/auction/domain/Auction.java
  core/src/main/java/dev/handsup/auction/dto/mapper/AuctionMapper.java
  core/src/main/java/dev/handsup/auction/exception/AuctionErrorCode.java
  core/src/main/java/dev/handsup/auction/repository/auction/AuctionRepository.java
  core/src/main/java/dev/handsup/auction/service/AuctionService.java
  core/src/main/java/dev/handsup/bidding/service/BiddingService.java
  core/src/main/java/dev/handsup/bookmark/domain/Bookmark.java
  core/src/main/java/dev/handsup/bookmark/dto/BookmarkMapper.java
  core/src/main/java/dev/handsup/bookmark/dto/EditBookmarkResponse.java
  core/src/main/java/dev/handsup/bookmark/dto/FindUserBookmarkResponse.java
  core/src/main/java/dev/handsup/bookmark/dto/GetBookmarkStatusResponse.java
  core/src/main/java/dev/handsup/bookmark/exception/BookmarkErrorCode.java
  core/src/main/java/dev/handsup/bookmark/repository/BookmarkRepository.java
  core/src/main/java/dev/handsup/bookmark/service/BookmarkService.java
  core/src/main/java/dev/handsup/common/dto/PageResponse.java
  core/src/test/java/dev/handsup/auction/repository/auction/AuctionQueryRepositoryImplTest.java
  core/src/test/java/dev/handsup/auction/repository/auction/AuctionRepositoryTest.java
  core/src/test/java/dev/handsup/auction/service/AuctionServiceTest.java
  core/src/test/java/dev/handsup/bidding/service/BiddingServiceTest.java
  core/src/test/java/dev/handsup/bookmark/service/BookmarkServiceTest.java
  core/src/testFixtures/java/dev/handsup/fixture/AuctionFixture.java
  core/src/testFixtures/java/dev/handsup/fixture/BookmarkFixture.java
Labels: feat

#38 [feat] : 경매 단건 조회 API 구현
  api/src/main/java/dev/handsup/auction/controller/AuctionApiController.java
  api/src/test/java/dev/handsup/auction/controller/AuctionApiControllerTest.java
  core/src/main/java/dev/handsup/auction/domain/Auction.java
  core/src/main/java/dev/handsup/auction/dto/mapper/AuctionMapper.java
  core/src/main/java/dev/handsup/auction/dto/response/AuctionDetailResponse.java
  core/src/main/java/dev/handsup/auction/dto/response/AuctionResponse.java
  core/src/main/java/dev/handsup/auction/dto/response/AuctionSimpleResponse.java
  core/src/main/java/dev/handsup/auction/service/AuctionService.java
  core/src/test/java/dev/handsup/auction/service/AuctionServiceTest.java
  core/src/testFixtures/java/dev/handsup/fixture/AuctionFixture.java
Labels: feat

#39 [feat] : 입찰 목록 전체 조회 API, 입찰 목록 상위 3개 조회 API
  api/src/main/java/dev/handsup/bidding/controller/BiddingApiController.java
  api/src/test/java/dev/handsup/bidding/controller/BiddingApiControllerTest.java
  core/src/main/java/dev/handsup/auction/dto/mapper/AuctionMapper.java
  core/src/main/java/dev/handsup/auction/dto/response/AuctionDetailResponse.java
  core/src/main/java/dev/handsup/auction/service/AuctionService.java
  core/src/main/java/dev/handsup/bidding/dto/BiddingMapper.java
  core/src/main/java/dev/handsup/bidding/dto/request/RegisterBiddingRequest.java
  core/src/main/java/dev/handsup/bidding/dto/response/BiddingResponse.java
  core/src/main/java/dev/handsup/bidding/repository/BiddingRepository.java
  core/src/main/java/dev/handsup/bidding/service/BiddingService.java
  core/src/test/java/dev/handsup/auction/service/AuctionServiceTest.java
  core/src/test/java/dev/handsup/bidding/service/BiddingServiceTest.java
  core/src/testFixtures/java/dev/handsup/fixture/AuctionFixture.java
Labels: feat

#42 [feat] : 인기 검색어 조회
  api/build.gradle
  api/src/main/java/dev/handsup/auction/controller/AuctionApiController.java
  api/src/main/java/dev/handsup/search/controller/SearchApiController.java
  api/src/test/java/dev/handsup/auction/controller/AuctionApiControllerTest.java
  api/src/test/java/dev/handsup/search/controller/SearchApiControllerTest.java
  core/build.gradle
  core/src/main/java/dev/handsup/auction/dto/mapper/AuctionMapper.java
  core/src/main/java/dev/handsup/auction/dto/request/AuctionSearchCondition.java
  core/src/main/java/dev/handsup/auction/exception/AuctionErrorCode.java
  core/src/main/java/dev/handsup/auction/repository/search/RedisSearchRepository.java
  core/src/main/java/dev/handsup/auction/service/AuctionService.java
  core/src/main/java/dev/handsup/search/domain/KeywordType.java
  core/src/main/java/dev/handsup/search/dto/PopularKeywordResponse.java
  core/src/main/java/dev/handsup/search/dto/PopularKeywordsResponse.java
  core/src/main/java/dev/handsup/search/dto/SearchMapper.java
  core/src/main/java/dev/handsup/search/service/SearchService.java
  core/src/main/resources/tmp.txt
  core/src/test/java/dev/handsup/auction/repository/auction/AuctionQueryRepositoryImplTest.java
  core/src/test/java/dev/handsup/auction/repository/search/RedisSearchRepositoryTest.java
  core/src/test/java/dev/handsup/auction/service/AuctionServiceTest.java
  core/src/test/java/dev/handsup/bidding/service/BiddingServiceTest.java
  core/src/test/java/dev/handsup/search/service/SearchServiceTest.java
Labels: feat

#43 [ fix] : 토큰 응답 & 요청에 Cookie 로직, 요청 토큰에 Bearer Type 추가
  api/src/main/java/dev/handsup/auction/controller/AuctionApiController.java
  api/src/main/java/dev/handsup/auth/controller/AuthApiController.java
  api/src/main/java/dev/handsup/auth/dto/AuthApiMapper.java
  api/src/main/java/dev/handsup/auth/dto/TokenReIssueApiRequest.java
  api/src/main/java/dev/handsup/auth/jwt/JwtAuthorizationArgumentResolver.java
  api/src/main/java/dev/handsup/auth/jwt/JwtInterceptor.java
  api/src/main/java/dev/handsup/bidding/controller/BiddingApiController.java
  api/src/main/java/dev/handsup/common/config/SwaggerConfig.java
  api/src/main/java/dev/handsup/user/controller/UserApiController.java
  api/src/test/java/dev/handsup/auction/controller/AuctionApiControllerTest.java
  api/src/test/java/dev/handsup/auth/JwtAuthorizationArgumentResolverTest.java
  api/src/test/java/dev/handsup/auth/JwtInterceptorTest.java
  api/src/test/java/dev/handsup/auth/controller/AuthApiControllerTest.java
  api/src/test/java/dev/handsup/bidding/controller/BiddingApiControllerTest.java
  api/src/test/java/dev/handsup/bookmark/controller/BookmarkApiControllerTest.java
  api/src/test/java/dev/handsup/common/support/ApiTestSupport.java
  api/src/test/java/dev/handsup/user/controller/UserApiControllerTest.java
  build.gradle
  core/src/main/java/dev/handsup/auction/domain/product/Product.java
  core/src/main/java/dev/handsup/auth/domain/Auth.java
  core/src/main/java/dev/handsup/auth/domain/BcryptImpl.java
  core/src/main/java/dev/handsup/auth/dto/AuthMapper.java
  core/src/main/java/dev/handsup/auth/dto/request/AuthRequest.java
  core/src/main/java/dev/handsup/auth/dto/request/LoginRequest.java
  core/src/main/java/dev/handsup/auth/dto/response/LoginDetailResponse.java
  core/src/main/java/dev/handsup/auth/dto/response/LoginSimpleResponse.java
  core/src/main/java/dev/handsup/auth/dto/response/TokenReIssueResponse.java
  core/src/main/java/dev/handsup/auth/exception/AuthErrorCode.java
  core/src/main/java/dev/handsup/auth/service/AuthService.java
  core/src/main/java/dev/handsup/auth/service/JwtProvider.java
  core/src/main/java/dev/handsup/user/service/UserService.java
  core/src/main/resources/tmp.txt
  core/src/test/java/dev/handsup/auth/service/AuthServiceTest.java
  core/src/test/java/dev/handsup/auth/service/JwtProviderTest.java
Labels: fix, refactor

#45 [feat] : 이미지 업로드 구현
  api/src/main/java/dev/handsup/image/controller/ImageController.java
  api/src/main/java/dev/handsup/image/dto/UploadImagesRequest.java
  api/src/main/java/dev/handsup/image/dto/UploadImagesResponse.java
  api/src/test/resources/application.yml
  core/build.gradle
  core/src/main/java/dev/handsup/common/config/S3Config.java
  core/src/main/java/dev/handsup/image/exception/ImageErrorCode.java
  core/src/main/java/dev/handsup/image/service/S3Service.java
  core/src/test/java/dev/handsup/image/service/S3ServiceTest.java
  core/src/test/resources/application.yml
Labels: feat

#47 [feat] : 경매 API 기능 추가 및 수정
  api/src/main/java/dev/handsup/image/controller/ImageController.java
  api/src/main/java/dev/handsup/search/controller/SearchApiController.java
  api/src/test/java/dev/handsup/auction/controller/AuctionApiControllerTest.java
  core/src/main/generated/dev/handsup/auction/domain/product/QProduct.java
  core/src/main/java/dev/handsup/auction/domain/Auction.java
  core/src/main/java/dev/handsup/auction/domain/product/Product.java
  core/src/main/java/dev/handsup/auction/domain/product/ProductImage.java
  core/src/main/java/dev/handsup/auction/dto/mapper/AuctionMapper.java
  core/src/main/java/dev/handsup/auction/dto/request/RegisterAuctionRequest.java
  core/src/main/java/dev/handsup/auction/dto/response/AuctionDetailResponse.java
  core/src/main/java/dev/handsup/auction/dto/response/AuctionSimpleResponse.java
  core/src/main/java/dev/handsup/bookmark/dto/BookmarkMapper.java
  core/src/main/java/dev/handsup/bookmark/dto/FindUserBookmarkResponse.java
  core/src/main/java/dev/handsup/bookmark/service/BookmarkService.java
  core/src/test/java/dev/handsup/auction/service/AuctionServiceTest.java
  core/src/testFixtures/java/dev/handsup/fixture/AuctionFixture.java
Labels: feat
